---
bb_repositories:
  - name: epel
    baseurl: https://dl.fedoraproject.org/pub/epel/10/Everything/$basearch/
    gpgcheck: false
  - name: bluebanquise
    baseurl: https://bluebanquise.com/repository/releases/latest/el10/x86_64/bluebanquise/
    gpgcheck: false
