---
# use '--limit c001' to restrict playbook to
# c001 if mg_computes contains multiple compute nodes
- name: computes
  hosts: "mg_computes"  # Will deploy on all mg_computes group nodes if no --limit
  roles:

    - role: bluebanquise.infrastructure.set_hostname
      tags: set_hostname
    - role: bluebanquise.infrastructure.nic
      tags: nic
    - role: bluebanquise.infrastructure.hosts_file
      tags: hosts_file
