---
# use '--limit management1' to restrict playbook to
# management1 if mg_managements contains multiple management nodes
- name: managements playbook
  hosts: "mg_managements"
  roles:

    - role: bluebanquise.infrastructure.set_hostname
      tags: set_hostname
